### ISSUE TITLE
Conflict with Dashmeter Pro

### ISSUE THREAD

**Issue by BattleGear** [Billiam/pygauge#2]
hi Billiam

first i have to say your project works flawless for me as a standalone and wanna say thanks for sharing this to the sim racing community :-)
ive modifyed your sketch a bit to invert the modul and defined pin 8 7 9 that the pin layout is compatible with other gauges and games ;-)
here is a pic of my system:
https://scontent-fra3-1.xx.fbcdn.net/hphotos-xpt1/t31.0-8/12891625_1020998974654625_3014925668936955841_o.jpg

but ive got a little problem with the gauge in combination with the gauge from dashmeter pro...
both use a cmd (bat) and only one of those workes at the same time...
so i want to ask you if you could please write a little program where is not based on the on a bat...

ive used a other tm1638 gauge and sketch for assetto corsa and it works in combination with dashmeter pro...
this is the project: http://batrako.blogspot.de/

ive you could make a gauge like this it would be a blast and brings your project one set forward ;-)

Ciao BattleGear

**Comment by Billiam** [comment]
Hi there!

The issue you're running into is that only one program at a time can connect to the dirt rally (I assume this is for dirt rally) data stream. This is a common problem for people using the same data to drive motion controllers, multiple gauges, etc.

So the bad news is that I can't fix it as part of this project. 
The good news is that other people have already done the hard work.

What you'll want to use is an application that connects to the outgauge server and acts as a proxy, allowing (multiple) gauges to receive the same data. I don't have any experience with these to recommend one, but if you search for codemasters outgauge proxy you should be able to find something. 

Good luck!
